---
with-expecter: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/ncotds/nco-qoordinator/internal/querycoordinator:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      Client: