---
name: PR check code

on:
  pull_request:
    branches:
      - '*'

jobs:

  lint:
    uses: ./.github/workflows/lint.yml

  test-unit:
    uses: ./.github/workflows/test-unit.yml

  test-publish-results:
    uses: ./.github/workflows/test-publish-gh.yml
    needs:
      - lint
      - test-unit
    if: ${{ always() }}

  test-publish-sonar:
    uses: ./.github/workflows/test-publish-sonar.yml
    needs:
      - lint
      - test-unit
    if: ${{ always() }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}