---
name: Publish tests report to SonarCloud

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  test-publish-sonar:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*

      - name: Publish to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}